"""Create 'first_name', 'last_name', 'avatar'

Revision ID: 61bf956df14a
Revises: a91699e93372
Create Date: 2021-09-10 16:46:36.986772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bf956df14a'
down_revision = 'a91699e93372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'avatar')
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###
